version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: workbuoy
      POSTGRES_PASSWORD: workbuoy
      POSTGRES_DB: workbuoy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workbuoy"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  db_data:
