version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wb
    ports:
      - "5432:5432"
    volumes:
      - wb_pg:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
      - mailhog
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/wb?schema=public
      MAILHOG_HOST: mailhog
      MAILHOG_PORT: 1025
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://backend:4000/api/v1
    ports:
      - "5173:5173"

volumes:
  wb_pg:
