paths:
  /api/v1/crm/import:
    post:
      summary: Batch import CRM entities
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema: { type: string }
        - in: header
          name: Idempotency-Key
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                entity: { type: string, enum: [contacts, opportunities] }
                dry_run: { type: boolean }
                file: { type: string, format: binary }
      responses: { '200': { description: OK } }
  /api/v1/crm/export:
    get:
      summary: Export CRM entities
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema: { type: string }
        - in: query
          name: entity
          schema: { type: string, enum: [contacts, opportunities] }
        - in: query
          name: format
          schema: { type: string, enum: [csv, json] }
      responses: { '200': { description: OK } }
  /api/v1/crm/dlq:
    get:
      summary: Fetch DLQ items
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema: { type: string }
        - in: query
          name: entity
          schema: { type: string }
        - in: query
          name: n
          schema: { type: integer }
      responses: { '200': { description: OK } }
