openapi: 3.0.3
info:
  title: Workbuoy Buoy API
  version: 1.0.0
paths:
  /buoy/complete:
    post:
      summary: Complete prompt
      responses:
        '200':
          description: Completion response