openapi: 3.0.3
info: { title: Buoy API, version: 1.0.0 }
paths:
  /buoy/complete:
    post:
      operationId: buoyComplete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text: { type: string }
      responses:
        '200': { description: ok }
        '403': { description: policy deny/degrade }
