openapi: 3.0.3
info:
  title: Workbuoy Suite - Buoy API
  version: 2.4.4
paths:
  /buoy/complete:
    post:
      summary: Run Buoy agent for a single intent
      operationId: buoyComplete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [intent]
              properties:
                intent: { type: string }
                params: { type: object, additionalProperties: true }
      responses:
        '200':
          description: Agent output
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: { type: object, additionalProperties: true }
                  explanations:
                    type: array
                    items:
                      type: object
                  confidence: { type: number }
                  correlationId: { type: string }
        '400': { description: Invalid request }
        '403': { description: Policy denied }
        '500': { description: Server error }
