openapi: 3.0.3
info:
  title: Workbuoy CRM API
  version: 1.0.0
paths:
  /api/crm/contacts:
    get:
      summary: List contacts
      responses:
        '200':
          description: OK
    post:
      summary: Create contact
      responses:
        '201':
          description: Created
  /api/crm/contacts/{id}:
    delete:
      summary: Delete contact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted