openapi: 3.0.3
info: { title: CRM API, version: 1.0.0 }
paths:
  /api/crm/contacts:
    get:
      operationId: listContacts
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema: { type: array, items: { type: object } }
    post:
      operationId: createContact
      responses:
        '201': { description: created }
        '403': { description: forbidden }
  /api/crm/contacts/{id}:
    delete:
      operationId: deleteContact
      parameters: [ { name: id, in: path, required: true, schema: { type: string } } ]
      responses:
        '204': { description: deleted }
        '403': { description: forbidden }
