openapi: 3.0.3
info: { title: Finance API, version: 1.0.0 }
paths:
  /api/finance/reminder/suggest:
    post:
      operationId: suggestReminder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                invoiceId: { type: string }
                customerEmail: { type: string }
      responses:
        '200':
          description: Reminder suggestion
          content:
            application/json:
              schema:
                type: object
                properties:
                  outcome: { type: object }
                  policy: { type: object }
