openapi: 3.0.3
info:
  title: Workbuoy Log API
  version: 1.0.0
paths:
  /api/logs:
    get:
      summary: List logs
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: OK
    post:
      summary: Append log
      responses:
        '201':
          description: Appended
  /api/audit/verify:
    get:
      summary: Verify audit chain
      responses:
        '200':
          description: Verification result