openapi: 3.0.3
info: { title: Log API, version: 1.0.0 }
paths:
  /api/logs:
    get: { operationId: listLogs, responses: { '200': { description: ok } } }
    post: { operationId: appendLog, responses: { '200': { description: appended } } }
  /api/audit/verify:
    get: { operationId: verifyAudit, responses: { '200': { description: ok } } }
