openapi: 3.0.3
info: { title: Workbuoy Log, version: 0.2.0 }
paths:
  /api/logs:
    get:
      operationId: listLogs
      parameters:
        - in: query
          name: limit
          schema: { type: integer, minimum: 1 }
        - in: query
          name: level
          schema: { type: string, enum: [info, warn, error] }
      responses: { '200': { description: OK } }
    post:
      operationId: appendLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [msg]
              properties:
                msg: { type: string }
                level: { type: string, enum: [info, warn, error] }
                meta: { type: object }
      responses: { '201': { description: Created }, '403': { description: Policy deny } }
  /api/audit/verify:
    get: { operationId: auditVerify, responses: { '200': { description: OK }, '500': { description: Broken chain } } }
