openapi: 3.0.3
info:
  title: Workbuoy Tasks API
  version: 1.0.0
paths:
  /api/tasks:
    get:
      summary: List tasks
      responses:
        '200':
          description: OK
    post:
      summary: Create task
      responses:
        '201':
          description: Created
  /api/tasks/{id}:
    patch:
      summary: Update task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted