openapi: 3.0.3
info: { title: Tasks API, version: 1.0.0 }
paths:
  /api/tasks:
    get: { operationId: listTasks, responses: { '200': { description: ok } } }
    post: { operationId: createTask, responses: { '201': { description: created }, '403': { description: forbidden } } }
  /api/tasks/{id}:
    patch:
      operationId: updateTask
      parameters: [ { name: id, in: path, required: true, schema: { type: string } } ]
      responses: { '200': { description: ok }, '403': { description: forbidden } }
    delete:
      operationId: deleteTask
      parameters: [ { name: id, in: path, required: true, schema: { type: string } } ]
      responses: { '204': { description: deleted }, '403': { description: forbidden } }
