openapi: 3.0.3
info: { title: Workbuoy Tasks, version: 0.2.0 }
paths:
  /api/tasks:
    get:
      operationId: listTasks
      parameters:
        - in: query
          name: status
          schema: { type: string, enum: [todo, doing, done] }
      responses: { '200': { description: OK } }
    post:
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title]
              properties:
                title: { type: string }
                status: { type: string, enum: [todo, doing, done] }
                assignee: { type: string }
                dueDate: { type: string, format: date-time }
      responses: { '201': { description: Created }, '403': { description: Policy deny } }
  /api/tasks/{id}:
    patch:
      operationId: patchTask
      parameters: [ { in: path, name: id, required: true, schema: { type: string } } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                status: { type: string, enum: [todo, doing, done] }
                assignee: { type: string }
                dueDate: { type: string, format: date-time }
      responses: { '200': { description: OK }, '403': { description: Policy deny }, '404': { description: Not found } }
    delete:
      operationId: deleteTask
      parameters: [ { in: path, name: id, required: true, schema: { type: string } } ]
      responses: { '204': { description: Deleted }, '403': { description: Policy deny }, '404': { description: Not found } }
