openapi: 3.1.0
info:
  title: WorkBuoy API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/v1/crm/contacts:
    get:
      summary: List contacts
      parameters: [{ name: x-tenant-id, in: header, required: true, schema: { type: string } }]
      responses: { '200': { description: OK } }
    post:
      summary: Create contact
      parameters: [{ name: x-tenant-id, in: header, required: true, schema: { type: string } }]
      responses: { '201': { description: Created } }
  /api/v1/crm/contacts/{id}:
    get: { summary: Get contact, parameters: [
      { name: x-tenant-id, in: header, required: true, schema: { type: string } },
      { name: id, in: path, required: true, schema: { type: string } }
    ], responses: { '200': { description: OK } } }
    patch: { summary: Update contact, parameters: [
      { name: x-tenant-id, in: header, required: true, schema: { type: string } },
      { name: id, in: path, required: true, schema: { type: string } }
    ], responses: { '200': { description: OK } } }
    delete: { summary: Delete contact, parameters: [
      { name: x-tenant-id, in: header, required: true, schema: { type: string } },
      { name: id, in: path, required: true, schema: { type: string } }
    ], responses: { '204': { description: No Content } } }
  /api/v1/crm/opportunities:
    get: { summary: List opportunities, parameters: [{ name: x-tenant-id, in: header, required: true, schema: { type: string } }], responses: { '200': { description: OK } } }
    post: { summary: Create opportunity, parameters: [{ name: x-tenant-id, in: header, required: true, schema: { type: string } }], responses: { '201': { description: Created } } }
  /api/v1/crm/pipelines:
    get: { summary: List pipelines, parameters: [{ name: x-tenant-id, in: header, required: true, schema: { type: string } }], responses: { '200': { description: OK } } }
    post: { summary: Create pipeline, parameters: [{ name: x-tenant-id, in: header, required: true, schema: { type: string } }], responses: { '201': { description: Created } } }
  /api/v1/crm/import:
    post: { summary: Batch import CSV/JSON, parameters: [{ name: x-tenant-id, in: header, required: true, schema: { type: string } }], responses: { '200': { description: OK } } }
  /api/v1/crm/export:
    get: { summary: Export JSON/CSV, parameters: [{ name: x-tenant-id, in: header, required: true, schema: { type: string } }], responses: { '200': { description: OK } } }
