apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workbuoy.fullname" . }}-flags
data:
  CRM_API_ENABLED: {{ .Values.env.CRM_API_ENABLED | quote }}
  CRM_IMPORT_EXPORT_ENABLED: {{ .Values.env.CRM_IMPORT_EXPORT_ENABLED | quote }}
  CONNECTORS_ENABLED: {{ .Values.env.CONNECTORS_ENABLED | quote }}
  SYNC_ENABLED: {{ .Values.env.SYNC_ENABLED | quote }}
  READ_ONLY_MODE: {{ .Values.env.READ_ONLY_MODE | quote }}
