{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workbuoy.fullname" . }}-secrets
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
