apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workbuoy.fullname" . }}
  labels: {{- include "workbuoy.labels" . | nindent 4 }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
