name: ci-cd
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: Unit tests (Jest) with coverage
        run: npm run test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: E2E tests (Playwright)
        run: npm run test:e2e
  docker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/wb-frontend:latest ./deploy/frontend
          docker build -t ghcr.io/${{ github.repository }}/wb-api:latest ./deploy/api
          docker push ghcr.io/${{ github.repository }}/wb-frontend:latest
          docker push ghcr.io/${{ github.repository }}/wb-api:latest
      - name: Deploy hook
        if: github.ref == 'refs/heads/main'
        run: curl -X POST ${{ secrets.DEPLOY_WEBHOOK_URL }}
