apiVersion: batch/v1
kind: CronJob
metadata:
  name: wb-signals-cron
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: signals
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: IfNotPresent
              command: ["node","scripts/scheduler.js"]
              env:
                - name: NODE_ENV
                  value: "production"
          restartPolicy: OnFailure
