{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "workbuoy.secretName" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "workbuoy.secretName" . }}
  data:
    - secretKey: databaseUrl
      remoteRef:
        key: {{ .Values.externalSecrets.keys.databaseUrl }}
    - secretKey: redisUrl
      remoteRef:
        key: {{ .Values.externalSecrets.keys.redisUrl }}
    - secretKey: siemEndpoint
      remoteRef:
        key: {{ .Values.externalSecrets.keys.siemEndpoint }}
    - secretKey: siemHmacSecret
      remoteRef:
        key: {{ .Values.externalSecrets.keys.siemHmacSecret }}
{{- end }}
