apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "workbuoy.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "workbuoy.fullname" . }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 443
