apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "workbuoy.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "workbuoy.fullname" . }}
