image:
  repository: ghcr.io/your-org/workbuoy
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "3000"

service:
  type: ClusterIP
  port: 3000
