name: alert-hygiene-lint

on:
  push:
    paths:
      - 'ops/alerts/**'
      - 'alertmanager/**'
      - 'grafana/dashboards/**'
      - '.github/workflows/alert-hygiene-lint.yml'
      - 'docs/ALERT_HYGIENE.md'
  pull_request:
    paths:
      - 'ops/alerts/**'
      - 'alertmanager/**'
      - 'grafana/dashboards/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint jq docker.io
      - name: Check YAML
        run: |
          yamllint ops/alerts || true
          yamllint alertmanager || true
      - name: promtool check rules
        run: |
          docker run --rm -v $PWD:/work prom/prometheus:latest promtool check rules /work/ops/alerts/rules/ingest.yaml
          docker run --rm -v $PWD:/work prom/prometheus:latest promtool check rules /work/ops/alerts/rules/errors.yaml
      - name: amtool check Alertmanager config
        run: |
          docker run --rm -v $PWD:/work prom/alertmanager:latest amtool check-config /work/alertmanager/config.yaml
      - name: Validate Grafana JSON
        run: jq . grafana/dashboards/ops_overview.json >/dev/null
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alert-hygiene
          path: |
            ops/alerts/rules/*.yaml
            alertmanager/config.yaml
            grafana/dashboards/ops_overview.json
            docs/ALERT_HYGIENE.md
