name: auto-merge
on:
  pull_request:
    types: [labeled, opened, ready_for_review, reopened, synchronize]

jobs:
  enable:
    if: contains(github.event.pull_request.labels.*.name, 'automerge') && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
