name: Backend Persistence CI

on:
  push:
    paths:
      - 'apps/backend/**'
      - 'prisma/**'
      - 'core/roles/**'
      - 'apps/backend/prisma/seed.ts'
      - 'scripts/roles-io.ts'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'apps/backend/**'
      - 'prisma/**'
      - 'core/roles/**'
      - 'apps/backend/prisma/seed.ts'
      - 'scripts/roles-io.ts'
      - '.github/workflows/**'

jobs:
  backend-persistence:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wb
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    env:
      FF_PERSISTENCE: 'true'
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/wb?schema=public
      ROLES_PATH: scripts/fixtures/minimal-roles.json
      FEATURES_PATH: scripts/fixtures/minimal-features.json
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache SWC artifacts
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/swc
          key: ${{ runner.os }}-swc-${{ hashFiles('package-lock.json') }}

      - name: Sanitize npm proxy config (legacy http-proxy)
        shell: bash
        run: scripts/ci/sanitize-npm-proxy.sh

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        env:
          PRISMA_CLI_QUERY_ENGINE_TYPE: binary
        run: npm run prisma:generate

      - name: Prisma migrate deploy
        env:
          PRISMA_CLI_QUERY_ENGINE_TYPE: binary
          DATABASE_URL: ${{ secrets.DATABASE_URL != '' && secrets.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/wb?schema=public' }}
        run: npm run -w @workbuoy/backend db:deploy

      - name: Seed baseline roles/features
        timeout-minutes: 10
        env:
          FF_PERSISTENCE: true
          DATABASE_URL: ${{ secrets.DATABASE_URL != '' && secrets.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/wb?schema=public' }}
          ROLES_PATH: scripts/fixtures/minimal-roles.json
          FEATURES_PATH: scripts/fixtures/minimal-features.json
        run: npm run -w @workbuoy/backend db:seed

      - name: Run persistence tests
        env:
          FF_PERSISTENCE: true
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: npm run test -w @workbuoy/backend -- --runInBand --passWithNoTests --detectOpenHandles
