name: Backend CI (in-memory)

on:
  push:
    paths: ['backend/**', 'src/**', 'tests/**', '.github/workflows/backend-ci.yml']
  pull_request:
    paths: ['backend/**', 'src/**', 'tests/**', '.github/workflows/backend-ci.yml']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      # In-memory smoke tests only (no DB required)
      - name: Run in-memory API smoke tests
        env:
          FF_PERSISTENCE: 'false'
        run: |
          npm test --             tests/features/active.api.test.ts             tests/usage/usage.api.test.ts             --runInBand --passWithNoTests
