name: Backend Persistence CI

on:
  push:
    paths:
      - 'backend/**'
      - 'prisma/**'
      - 'core/roles/**'
      - 'scripts/seed-roles-from-json.ts'
      - 'scripts/seed-roles-lib.ts'
      - 'scripts/roles-io.ts'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'prisma/**'
      - 'core/roles/**'
      - 'scripts/seed-roles-from-json.ts'
      - 'scripts/seed-roles-lib.ts'
      - 'scripts/roles-io.ts'
      - '.github/workflows/**'

jobs:
  backend-persistence:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wb
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      FF_PERSISTENCE: 'true'
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/wb?schema=public
      ROLES_PATH: core/roles/roles.json
      FEATURES_PATH: core/roles/features.json
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install --no-audit --fund=false

      - name: Install backend dependencies
        run: npm --prefix backend install --no-audit --fund=false

      - name: Generate Prisma client
        env:
          PRISMA_CLI_QUERY_ENGINE_TYPE: binary
        run: npx --yes -p prisma@6.16.2 prisma generate --schema=backend/prisma/schema.prisma

      - name: Apply Prisma migrations
        env:
          PRISMA_CLI_QUERY_ENGINE_TYPE: binary
        run: npx --yes -p prisma@6.16.2 prisma migrate deploy --schema=backend/prisma/schema.prisma

      - name: Seed baseline roles/features
        run: npm run seed:roles

      - name: Run persistence tests
        working-directory: backend
        run: npx jest --config jest.meta.config.cjs --runInBand --passWithNoTests
