name: Backend CI (in-memory)

on:
  push:
    paths:
      - 'backend/**'
      - 'prisma/**'
      - 'core/roles/**'
      - 'scripts/seed-roles-from-json.ts'
      - 'scripts/seed-roles-lib.ts'
      - 'scripts/roles-io.ts'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'prisma/**'
      - 'core/roles/**'
      - 'scripts/seed-roles-from-json.ts'
      - 'scripts/seed-roles-lib.ts'
      - 'scripts/roles-io.ts'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FF_PERSISTENCE: 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install --no-audit --fund=false

      - name: Install backend dependencies
        run: npm --prefix backend install --no-audit --fund=false

      - name: Run backend Jest suite
        env:
          ROLES_PATH: ./scripts/fixtures/minimal-roles.json
          FEATURES_PATH: ./scripts/fixtures/minimal-features.json
        run: npm --prefix backend test -- --runInBand --passWithNoTests
