name: Backend CI (in-memory)

on:
  push:
    paths:
      - 'apps/backend/**'
      - 'prisma/**'
      - 'core/roles/**'
      - 'scripts/seed-roles-from-json.ts'
      - 'scripts/seed-roles-lib.ts'
      - 'scripts/roles-io.ts'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'apps/backend/**'
      - 'prisma/**'
      - 'core/roles/**'
      - 'scripts/seed-roles-from-json.ts'
      - 'scripts/seed-roles-lib.ts'
      - 'scripts/roles-io.ts'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FF_PERSISTENCE: 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache SWC artifacts
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/swc
          key: ${{ runner.os }}-swc-${{ hashFiles('package-lock.json') }}

      - name: Sanitize npm proxy config (legacy http-proxy)
        shell: bash
        run: scripts/ci/sanitize-npm-proxy.sh

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npm run prisma:generate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/wb?schema=public

      - name: Backend typecheck
        run: npm run typecheck -w @workbuoy/backend

      - name: Backend smoke tests (in-memory)
        env:
          FF_PERSISTENCE: '0'
          WB_CHAOS_READY: '0'
          SMOKE_PORT: 3100
        run: npm run -w @workbuoy/backend test:smoke

      - name: Run backend Jest suite
        env:
          ROLES_PATH: ./scripts/fixtures/minimal-roles.json
          FEATURES_PATH: ./scripts/fixtures/minimal-features.json
        run: npm run test -w @workbuoy/backend -- --passWithNoTests --detectOpenHandles
