name: backend-ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Force clean npm config
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          npm config set fund false
          npm config set audit false
          npm config get registry

      - name: Install dependencies
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-fund --no-audit
          fi

      - name: Run smoke tests (temporary)
        working-directory: backend
        run: npx jest --ci --config jest.ci.config.cjs

  - name: Run tests
    working-directory: backend
    run: npm test

  - name: Run typecheck
    working-directory: backend
    run: npm run typecheck
