name: backend-ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "No package-lock.json found; running npm install"
            npm install --no-fund --no-audit
          fi

      - name: Typecheck (optional)
        working-directory: backend
        run: npm run typecheck --if-present

      - name: Lint (optional)
        working-directory: backend
        run: npm run lint --if-present

      - name: Build (optional)
        working-directory: backend
        run: npm run build --if-present

      - name: Test
        working-directory: backend
        run: npm test -- --ci
