name: backend-persistence

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  backend-persistence:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wb
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      FF_PERSISTENCE: "true"
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/wb?schema=public
      # 👇 pek direkte til rollene slik at seed ALDRI feiler på path
      ROLES_PATH: core/roles/roles.json
      FEATURES_PATH: core/roles/features.json
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root deps
        run: npm install
      - name: Install backend deps
        run: npm --prefix backend install
      - name: Generate Prisma client
        run: npx prisma generate --schema=prisma/schema.prisma
      - name: Seed baseline roles (via tsx)
        run: npm run seed:roles
      # (valgfritt) kjør persistens-tester her hvis dere har dem
      # - run: npm test -- --runInBand
