name: backend-ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      prisma: ${{ steps.filter.outputs.prisma }}
      roles: ${{ steps.filter.outputs.roles }}
      backend_related: ${{ steps.compute.outputs.backend_related }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            prisma:
              - 'prisma/**'
            roles:
              - 'core/roles/**'
              - 'scripts/seed-roles-from-json.ts'
      - name: compute backend_related
        id: compute
        run: |
          if [ "${{ steps.filter.outputs.backend }}" = "true" ] || \
             [ "${{ steps.filter.outputs.prisma }}" = "true" ] || \
             [ "${{ steps.filter.outputs.roles }}" = "true" ]; then
            echo "backend_related=true" >> $GITHUB_OUTPUT
          else
            echo "backend_related=false" >> $GITHUB_OUTPUT
          fi

  test:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm --prefix backend install
      - run: npm run --if-present lint
      - run: npm run --if-present typecheck
      - run: npm run --if-present test

  test-persistence:
    needs: changes
    if: needs.changes.outputs.backend_related == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm --prefix backend install
      - run: echo "persistence-style tests would run here only when backend/prisma/roles changed"
