name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Typecheck (if present)
        run: npm run typecheck --if-present

      - name: Check roles (non-blocking)
        run: npm run check:roles --if-present
        continue-on-error: true

      - name: Backend tests
        run: npm --prefix backend test -- --runInBand --passWithNoTests

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run coverage (if present)
        run: npm run test --workspaces --if-present -- --coverage
