name: backend-ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install deps (ci if lockfile, else install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "No package-lock.json found; running npm install"
            npm install --no-fund --no-audit
          fi
      - name: Typecheck (optional)
        run: npm run typecheck --if-present
      - name: Lint (optional)
        run: npm run lint --if-present
      - name: Build (optional)
        run: npm run build --if-present
      - name: Test
        run: npm test -- --ci
