name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run --if-present lint
      - run: npm run --if-present typecheck
      - run: npm run --if-present test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run test -- --coverage

  backend-persistence:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wb
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      FF_PERSISTENCE: "true"
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/wb?schema=public
      ROLES_PATH: core/roles/roles.json
      FEATURES_PATH: core/roles/features.json
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (no lockfile required)
        run: npm install
      - name: Generate Prisma client
        run: npx prisma generate --schema=prisma/schema.prisma
      - name: Seed baseline roles (via tsx)
        run: npm run seed:roles
