name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  frontend-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'apps/frontend/**'
              - 'package.json'

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install workspaces
        run: npm install --workspaces --include-workspace-root --no-audit --fund=false

      - name: Check roles JSON (non-blocking)
        run: npm run --if-present check:roles
        continue-on-error: true

      - name: Prettier format check (non-blocking)
        run: npm run format
        continue-on-error: true

      - name: Lint
        run: npm run lint

      - name: Typecheck (meta config)
        run: npm run typecheck:meta --if-present

      - name: Backend unit tests
        env:
          FF_PERSISTENCE: 'false'
        run: npm run test -w @workbuoy/backend -- --runInBand --passWithNoTests

  coverage:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install workspaces
        run: npm install --workspaces --include-workspace-root --no-audit --fund=false

      - name: Backend tests with coverage
        env:
          FF_PERSISTENCE: 'false'
        run: npm run test -w @workbuoy/backend -- --coverage --runInBand --passWithNoTests

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: |
            apps/backend/coverage/**
            coverage/**

  frontend-typecheck:
    needs:
      - frontend-changes
      - lint-and-test
    if: needs.frontend-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install workspaces
        run: npm install --workspaces --include-workspace-root

      - name: Frontend typecheck (non-blocking)
        run: npm run typecheck -w @workbuoy/frontend
        continue-on-error: true
