name: compliance-api-tests

on:
  push:
    paths: ['backend/src/compliance/**', 'backend/tests/**', 'backend/package.json', 'docs/compliance/**', '.github/workflows/compliance-api-tests.yml']
  pull_request:
    paths: ['backend/src/compliance/**', 'backend/tests/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
        working-directory: backend
      - name: Build
        run: npm run build
        working-directory: backend
      - name: Tests
        run: npx jest --passWithNoTests
        working-directory: backend
