name: containers-sign

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/containers-sign.yml'
  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/workbuoy-backend

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for keyless signing
      contents: read
      packages: write   # push to GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          SHA="${GITHUB_SHA::12}"
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "tag=sha-$SHA" >> $GITHUB_OUTPUT

      - name: Build & push (mock image)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}
          file: ./Dockerfile
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.3'
      - name: Sign image (keyless)
        run: |
          cosign sign --yes $IMAGE_NAME:${{ steps.meta.outputs.tag }}
      - name: Attach build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.meta.outputs.tag }}
          push-to-registry: true
