name: crm-model-tests

on:
  push:
    paths: ['backend/**', 'docs/CRM_MODEL.md', '.github/workflows/crm-model-tests.yml', 'openapi/workbuoy.yaml']
  pull_request:
    paths: ['backend/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
        working-directory: backend
      - name: Build
        run: npm run build
        working-directory: backend
      - name: Migrate
        run: npm run migrate
        working-directory: backend
      - name: Test
        run: npm test
        working-directory: backend
