name: crm-observability-tests

on:
  push:
    paths: ['backend/src/**', 'backend/tests/**', 'backend/package.json', '.github/workflows/crm-observability-tests.yml', 'docs/OBSERVABILITY_CRM.md', 'ops/dashboards/workbuoy_crm_observability.json']
  pull_request:
    paths: ['backend/src/**', 'backend/tests/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
        working-directory: backend
      - name: Build
        run: npm run build
        working-directory: backend
      - name: Test metrics exposure
        run: npm test
        working-directory: backend
