name: desktop-e2e-load

on:
  push:
    paths:
      - 'scripts/**'
      - 'desktop/**'
      - '.github/workflows/desktop-e2e-load.yml'
      - 'docs/DESKTOP_TESTS_E2E.md'
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Conflict E2E (LWW)
        run: |
          node scripts/desktop_e2e_conflict_test.js
          test -f reports/desktop_conflict.json
          cat reports/desktop_conflict.json
      - name: Load test 1200 ops
        env:
          LOAD_OPS: 1200
        run: |
          node scripts/desktop_load_test.js
          cat reports/desktop_sync_load.json
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: desktop-e2e-reports
          path: reports/**
