name: desktop-builds

on:
  push:
    paths: ['desktop/**', '.github/workflows/desktop-builds.yml']
  pull_request:
    paths: ['desktop/**']

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
        working-directory: desktop
      - name: Disable Mac signing (if mac)
        if: matrix.os == 'macos-latest'
        run: echo "CSC_IDENTITY_AUTO_DISCOVERY=false" >> $GITHUB_ENV
      - name: Build dist
        run: npm run dist
        working-directory: desktop
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}-artifacts
          path: desktop/release/**
