name: e2e-green

on:
  push:
    paths:
      - 'scripts/**'
      - 'desktop_demo/**'
      - '.github/workflows/e2e-green.yml'
      - 'docs/E2E_GREEN.md'
  pull_request:
    paths:
      - 'scripts/**'
      - 'desktop_demo/**'

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run E2E green path
        run: |
          chmod +x scripts/e2e_green_path.sh
          ./scripts/e2e_green_path.sh
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: e2e-green-reports
          path: reports/**
