name: frontend-unit

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-unit.yml'
  push:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👇 Sett opp Node UTEN cache (fjerner "paths not resolved"-feilen)
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Verify lockfile (optional)
        run: |
          ls -la
          [ -f package.json ] || (echo "No package.json in ./frontend" && exit 1)
          echo "Lockfile present?"; ls -1 package-lock.json || true

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --omit=optional --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Unit tests
        run: npm run test --if-present
