name: frontend-unit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      CI: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --omit=optional --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        run: npm run test
