name: frontend-unit

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-unit.yml'
  push:
    branches: [ main ]

jobs:
  unit:
    # Skip job hvis frontend-workspace ikke finnes i denne PR-en
    if: ${{ hashFiles('frontend/package.json') != '' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      CI: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Cache SWC artifacts
        uses: actions/cache@v4
        with:
          path: frontend/node_modules/.cache/swc
          key: ${{ runner.os }}-swc-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --omit=optional --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        run: npm run test
