name: helm-lint

on:
  push:
    paths: ['ops/helm/workbuoy/**', '.github/workflows/helm-lint.yml']
  pull_request:
    paths: ['ops/helm/workbuoy/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.4'
      - name: Helm Lint
        run: helm lint ops/helm/workbuoy
      - name: Helm Template
        run: helm template workbuoy ops/helm/workbuoy --values ops/helm/workbuoy/values.yaml
