name: helm-validate

on:
  push:
    paths: ['ops/helm/workbuoy/**', '.github/workflows/helm-validate.yml', 'ops/dashboards/**', 'docs/DEPLOY_HELM.md']
  pull_request:
    paths: ['ops/helm/workbuoy/**']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Lint chart
        run: helm lint ops/helm/workbuoy
      - name: Render templates (staging)
        run: helm template workbuoy ops/helm/workbuoy -f ops/helm/workbuoy/values-staging.yaml > rendered-staging.yaml
      - name: Render templates (prod)
        run: helm template workbuoy ops/helm/workbuoy -f ops/helm/workbuoy/values-prod.yaml > rendered-prod.yaml
      - name: Install kubeval
        run: |
          curl -sSL -o kubeval.tar.gz https://github.com/instrumenta/kubeval/releases/download/0.16.1/kubeval-linux-amd64.tar.gz
          tar -xzf kubeval.tar.gz
          sudo mv kubeval /usr/local/bin/
      - name: Validate manifests
        run: |
          kubeval rendered-staging.yaml --ignore-missing-schemas
          kubeval rendered-prod.yaml --ignore-missing-schemas
      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: |
            rendered-staging.yaml
            rendered-prod.yaml
