name: import-export-tests

on:
  push:
    paths: ['backend/src/crm/import_export_routes.ts', 'backend/tests/import_export.test.ts', 'backend/package.json', '.github/workflows/import-export-tests.yml']
  pull_request:
    paths: ['backend/src/crm/import_export_routes.ts', 'backend/tests/import_export.test.ts']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
        working-directory: backend
      - name: Build
        run: npm run build
        working-directory: backend
      - name: Test
        run: npm test
        working-directory: backend
