name: lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - name: Security audit (report only)
        run: npm audit --omit=dev || true
      - name: ESLint (shippable workspaces) — blocking
        run: npm run lint
