name: lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - name: ESLint (apps/*) — blocking
        run: npm run lint:apps

  lint-satellites:
    runs-on: ubuntu-latest
    continue-on-error: true # non-blocking by design
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - name: ESLint (repo-wide) — non-blocking report
        run: npm run lint
