name: meta-foundation

on:
  workflow_dispatch:
    inputs:
      enable_docgen:
        description: "Run docgen"
        required: true
        default: "false"
      enable_planner:
        description: "Run planner"
        required: true
        default: "false"
      enable_builder:
        description: "Run builder (proposals only)"
        required: true
        default: "false"

jobs:
  meta-logs-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate jsonl
        run: |
          jq -c . meta/decision-log.jsonl >/dev/null 2>&1 || true
          jq -c . meta/usage-log.jsonl >/dev/null 2>&1 || true

  docgen:
    if: ${{ github.event.inputs.enable_docgen == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci || true
      - run: node tools/docgen/docgen.ts
      - uses: peter-evans/create-pull-request@v6
        with:
          title: "docs: auto-update (docgen)"
          branch: chore/auto-docs
          commit-message: "docs: auto-update"

  planner:
    if: ${{ github.event.inputs.enable_planner == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: node services/planner/planner.ts
      - uses: actions/upload-artifact@v4
        with:
          name: planner-subtasks
          path: services/planner/subtasks

  builder-proposal:
    if: ${{ github.event.inputs.enable_builder == 'true' }}
    needs: planner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - uses: actions/download-artifact@v4
        with:
          name: planner-subtasks
          path: services/planner/subtasks
      - run: |
          git config user.name "workbuoy-bot"
          git config user.email "bot@workbuoy.io"
          node services/builder/builder.ts
      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "ai: proposal (docs/tests/scripts only)"
          branch: chore/ai-proposal
          labels: ai-proposal
          body: "Generated by builder. Human review required."
