name: OpenAPI Lint (Redocly)

on:
  push:
    paths: ['openapi/**', '.github/workflows/openapi-lint.yml']
  pull_request:
    paths: ['openapi/**', '.github/workflows/openapi-lint.yml']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Redocly CLI
        run: npm i -g @redocly/cli@latest
      - name: Lint OpenAPI (each file under openapi/)
        run: |
          if [ -d openapi ]; then
            set -e
            found=false
            while IFS= read -r f; do
              found=true
              echo "Linting $f"
              redocly lint "$f" --format=stylish
            done < <(find openapi -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \))
            if [ "$found" = false ]; then
              echo "No OpenAPI files found under openapi/"
            fi
          else
            echo "openapi/ directory not found; skipping"
          fi
