name: OpenAPI Lint

on:
  push:
    paths: ['openapi/**', '.github/workflows/openapi-lint.yml']
  pull_request:
    paths: ['openapi/**', '.github/workflows/openapi-lint.yml']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate OpenAPI
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: openapi/openapi.yaml
        env:
          PUPPETEER_ARGS: --no-sandbox
