jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Redocly CLI
        run: npm i -g @redocly/cli@latest

      # 👉 Kjør kun hvis det faktisk finnes filer
      - name: Check if OpenAPI files exist
        id: has_files
        run: |
          if ls openapi/**/*.{yaml,yml,json} >/dev/null 2>&1; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Lint OpenAPI (per file, soft)
        if: steps.has_files.outputs.found == 'true'
        continue-on-error: true           # 👈 gjør lint ikke-blokkerende
        run: |
          set +e
          find openapi -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) \
            -exec sh -c 'echo "Linting $1"; redocly lint "$1" --format=stylish || true' _ {} \;
