name: openapi-sdk

on:
  push:
    paths: ['openapi/**', 'backend/src/docs/**', 'backend/package.json', 'docs/API_SPECS.md', '.github/workflows/openapi-sdk.yml']
  pull_request:
    paths: ['openapi/**']

jobs:
  build-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node deps
        run: npm ci
        working-directory: backend
      - name: Validate OpenAPI
        run: npm run validate:openapi
        working-directory: backend
      - name: Generate TS SDK
        run: npm run gen:sdk:ts
        working-directory: backend
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install openapi-python-client
        run: pip install openapi-python-client
      - name: Generate Python SDK
        run: npm run gen:sdk:py
        working-directory: backend
      - name: Upload SDKs
        uses: actions/upload-artifact@v4
        with:
          name: workbuoy-sdks
          path: |
            sdk/ts-gen/**
            sdk/python-gen/**
