name: policy-meta-rails

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
      - 'ci/policy-meta-rails.sh'
      - '.github/workflows/policy-meta-rails.yml'
  pull_request:
    paths:
      - 'apps/backend/**'
      - 'ci/policy-meta-rails.sh'
      - '.github/workflows/policy-meta-rails.yml'

jobs:
  meta-rails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Verify META rails guards
        run: ci/policy-meta-rails.sh
