name: policy-meta-rails

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  meta-rails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify META rails guards
        run: ci/policy-meta-rails.sh
