name: pr-preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Kube config
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
      - name: Namespace
        run: |
          NS=wb-pr-${{ github.event.number }}
          kubectl create ns "$NS" || true
          echo "$NS" > ns.txt
      - name: Helm deploy
        run: |
          NS=$(cat ns.txt)
          helm upgrade --install wb-pr ops/helm/workbuoy -f release/values/values.stage.yaml -n "$NS"
      - name: Preview URL
        run: echo "https://wb-pr-${{ github.event.number }}.stage.workbuoy.io" > preview_url.txt
      - uses: actions/upload-artifact@v4
        with:
          name: preview-url
          path: preview_url.txt
  teardown:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Namespace delete
        run: |
          NS=wb-pr-${{ github.event.number }}
          kubectl delete ns "$NS" --ignore-not-found
