name: workbuoy-release-orchestrate (skeleton)
on:
  workflow_dispatch:
    inputs:
      modules:
        description: 'saas,crm,desktop (comma-separated)'
        default: 'saas,crm,desktop'
        required: true
      environment:
        description: 'stage or prod'
        default: 'stage'
        required: true
jobs:
  # This is a skeleton; wire secrets and commands in your secure runner.
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "resolve flags here"
  gates:
    runs-on: ubuntu-latest
    steps:
      - name: Roles gate
        run: echo "node core/roles/validate_roles.js"
      - name: SaaS smoke
        run: echo "see tests/saas/smoke_saas.yaml"
      - name: CRM smoke
        run: echo "see tests/crm/smoke_crm.yaml"
      - name: Desktop E2E
        run: echo "see tests/desktop/e2e_desktop_conflict_load.yaml"
