name: repo-guards

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ban-tracked-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enforce no tracked node_modules
        run: npm run guard:ban-tracked-deps
      - name: Enforce large file policy (>5MB)
        run: GUARD_MAX_FILE_BYTES=$((5 * 1024 * 1024)) npm run guard:ban-large-files
  orphan-workspaces:
    runs-on: ubuntu-latest
    needs: ban-tracked-deps
    steps:
      - uses: actions/checkout@v4
      - name: Report orphan workspaces (non-blocking)
        run: npm run guard:orphan-workspaces
