name: sbom

on:
  push:
    branches: [ main ]
    paths:
      - 'ops/bom/**'
      - '.github/workflows/sbom.yml'
      - '**.json'
      - '**.js'
      - '**.ts'
  workflow_dispatch: {}

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM (CycloneDX & SPDX) with Syft
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom.cdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cdx.json
