name: sdk-js

on:
  push:
    paths: ['sdk/js/**', '.github/workflows/sdk-js.yml']
  pull_request:
    paths: ['sdk/js/**']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk/js
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run build
      - run: npm test
