name: sdk-py

on:
  push:
    paths: ['sdk/python/**', '.github/workflows/sdk-py.yml']
  pull_request:
    paths: ['sdk/python/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m venv .venv
      - run: . .venv/bin/activate && pip install -e ./sdk/python && pytest -q
