name: security-hardening-tests

on:
  push:
    paths: ['backend/src/security/**', 'backend/tests/**', 'docs/SECURITY_HARDENING.md', '.github/workflows/security-hardening-tests.yml', 'backend/package.json']
  pull_request:
    paths: ['backend/src/security/**', 'backend/tests/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
        working-directory: backend
      - name: Build
        run: npm run build
        working-directory: backend
      - name: Test
        run: npx jest --passWithNoTests
        working-directory: backend
