name: smoke-open-pr

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run smoke test
        run: echo "✅ Smoke test ran successfully"
