name: Smoke Open PR

on:
  workflow_dispatch:

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(ci): automerge smoke"
          branch: smoke/automerge-test
          title: "chore(ci): automerge smoke"
          body: "Smoke test PR to verify automerge pipeline."
          labels: automerge
